export const helperConstants = {
  THEME_CHANGE_REQUEST: "THEME_CHANGE_REQUEST",
  MARGIN_CHANGE_REQUEST: "MARGIN_CHANGE_REQUEST",
  FILTER_CHANGE_REQUEST: "FILTER_CHANGE_REQUEST",
  PAGE_CHANGE_REQUEST: "PAGE_CHANGE_REQUEST",
  ADD_VEHICLE_CHANGE_REQUEST: "ADD_VEHICLE_CHANGE_REQUEST",
};

export const vehicleConstants = {
  GET_VEHICLES_REQUEST: "GET_VEHICLES_REQUEST",
  GET_VEHICLES_SUCCESS: "GET_VEHICLES_SUCCESS",
  GET_VEHICLES_FAILURE: "GET_VEHICLES_FAILURE",
  GET_MORE_VEHICLES_REQUEST: "GET_MORE_VEHICLES_REQUEST",
  GET_MORE_VEHICLES_SUCCESS: "GET_MORE_VEHICLES_SUCCESS",
  GET_MORE_VEHICLES_FAILURE: "GET_MORE_VEHICLES_FAILURE",
  GET_VEHICLE_DETAILS_REQUEST: "GET_VEHICLE_DETAILS_REQUEST",
  GET_VEHICLE_DETAILS_SUCCESS: "GET_VEHICLE_DETAILS_SUCCESS",
  GET_VEHICLE_DETAILS_FAILURE: "GET_VEHICLE_DETAILS_FAILURE",
  POPULATE_VEHICLES_REQUEST: "POPULATE_VEHICLES_REQUEST",
  POPULATE_VEHICLES_SUCCESS: "POPULATE_VEHICLES_SUCCESS",
  POPULATE_VEHICLES_FAILURE: "POPULATE_VEHICLES_FAILURE",
  PATCH_VEHICLE_REQUEST: "PATCH_VEHICLE_REQUEST",
  PATCH_VEHICLE_SUCCESS: "PATCH_VEHICLE_SUCCESS",
  PATCH_VEHICLE_FAILURE: "PATCH_VEHICLE_FAILURE",
  POST_VEHICLE_REQUEST: "POST_VEHICLE_REQUEST",
  POST_VEHICLE_SUCCESS: "POST_VEHICLE_SUCCESS",
  POST_VEHICLE_FAILURE: "POST_VEHICLE_FAILURE",
  RESET_ALL_SUCCESS: "RESET_ALL_SUCCESS",
};
